### ISSUE TITLE
Do we need a tag?

### ISSUE THREAD

**Issue by pbek** [flathub/org.qownnotes.QOwnNotes#1]
@stobbsm, do we need a tag (because that is generated by TravisCI, isn't maybe the commit number enough?

https://github.com/flathub/org.qownnotes.QOwnNotes/blob/080dbc74b4b432e3f3e8218d2566be846454886e/org.qownnotes.QOwnNotes.json#L26

**Comment by nedrichards** [comment]
Flathub just wants 'stable versions'. So long as you can refer to that in a stable reproducible fashion the implementation is, toa certain extent up to you and your release process. Tags are great - but you need a commit as well. A commit on it's own is fine, so long as it's not just pointing to a random commit without a reason. If you release archives you can point to that as well.

**Comment by pbek** [comment]
Thanks for the clarification!

**Comment by stobbsm** [comment]
I think the tag is good for maintaining a clear understanding of what's going on. Archives could be fine to use. I'll take a look at using archives.

**Comment by pbek** [comment]
I don't really use tags, but I do create source archives (automatically) for each release.

**Comment by nedrichards** [comment]
As a bonus, the archive is usually a bit quicker to download and setup for the builder.

**Comment by stobbsm** [comment]
Just made the last commit to use tags and commit numbers. From here on out, I'll use the archive when updating this package.

**Comment by pbek** [comment]
Great, thank you!
