### ISSUE TITLE
Please update QOwnNotes to a recent release

### ISSUE THREAD

**Issue by brx75** [flathub/org.qownnotes.QOwnNotes#11]
Please update QOenNotes to a recente release.
Currently 19.11.10 is available.

**Comment by pbek** [comment]
If someone creates a script that takes the version number and the hash as parameters, downloads this repository, updates the necessary files, commits the changes and does a git push then I would make it part of the build process.

**Comment by stobbsm** [comment]
If will update shortly. Runs on a schedule to not overwhelm my build server with checks.

**Comment by pbek** [comment]
In a few minutes there will be 19.11.11 released. :grin:

**Comment by stobbsm** [comment]
I'll hold off for a few minutes then. 👍

**Comment by pbek** [comment]
It's out. `e52f34138c45619c737666c19d584fbd586b3c95b79f2da95f35a65b43c47ff4`

**Comment by stobbsm** [comment]
Did find a sorting issue with the update app. Fixed it, and it should be latest releases from now on.

**Comment by barthalion** [comment]
@stobbsm Is your script public?

**Comment by stobbsm** [comment]
Go application, at https://gitlab.com/stobbsm/update-qownnotes-flatpak

**Comment by pbek** [comment]
Nice one!

**Comment by barthalion** [comment]
Thanks!
