### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by eszlari** [flathub/org.qownnotes.QOwnNotes#14]
```
flatpak run org.freedesktop.appstream-glib validate builddir/*/share/appdata/org.qownnotes.QOwnNotes.appdata.xml
 in dir /srv/buildbot/worker/build-x86_64-2/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run org.freedesktop.appstream-glib validate builddir/*/share/appdata/org.qownnotes.QOwnNotes.appdata.xml'
 using PTY: False
builddir/files/share/appdata/org.qownnotes.QOwnNotes.appdata.xml: FAILED:
• attribute-missing     : <release> has no timestamp
Validation of files failed
program finished with exit code 1
elapsedTime=0.192714
```

**Comment by Erick555** [comment]
ping @stobbsm

**Comment by penyuan** [comment]
On Flathub.org, the version is still 20.9.11, probably because the build fails?

How can we help fix this? @stobbsm and others please advise. Thanks!

**Comment by pbek** [comment]
It seems like the `date` isn't set any more. Is there a way to fix that, @stobbsm?

https://github.com/flathub/org.qownnotes.QOwnNotes/blob/fd131bb05164cf77c4d702d28d1729e0d7fcebc8/org.qownnotes.QOwnNotes.appdata.xml#L41-L56

**Comment by Justinzobel** [comment]
20.11.5 is out as well.

**Comment by stobbsm** [comment]
Must be an issue in the auto update code. I'll check it out when I can, but 
things are pretty insane for me at the moment.

**Comment by pbek** [comment]
Awesome, thanks a lot @stobbsm! 😁

**Comment by penyuan** [comment]
Thank you @stobbsm! Let us know how we can help.

**Comment by stobbsm** [comment]
Finally got a chance to update. Fixed the updater app, and will be setting up ci tomorrow.

It builds, uses the correct version, and all.

**Comment by pbek** [comment]
Thank you very much, @stobbsm!

**Comment by penyuan** [comment]
Thank you @stobbsm, fantastic! 🙏🏼 👏🏼
