### ISSUE TITLE
Can you please update the flatpack version to the latest application version?

### ISSUE THREAD

**Issue by codeRetard** [flathub/org.qownnotes.QOwnNotes#16]
Hi,

As the title suggests, can you please update the flatpack version to the latest available version? I reply entirely on flatpacks for many applications, including QOwnNotes, and my only one gripe with QOwnNotes is that it is almost always lagging behind the App release cycle by many versions.

**Current App version: 21.2.5**
**Current Flatpack Version: 21.1.8**

**Comment by andyhubbert941** [comment]
Hi

appreciate the time put into this flatpak but like the user above can we have a version bump to the latest code base please?

Any way of us doing this as users? Pull request etc? Let me know and although not massively knowledgeable with flatpak will give it a go if you can point me in the right direction!

Many thanks for your time and hard work!

**Comment by andyhubbert941** [comment]
> Hi,
> 
> As the title suggests, can you please update the flatpack version to the latest available version? I reply entirely on flatpacks for many applications, including QOwnNotes, and my only one gripe with QOwnNotes is that it is almost always lagging behind the App release cycle by many versions.
> 
> **Current App version: 21.2.5**
> **Current Flatpack Version: 21.1.8**

All updated @codeRetard - try it out!
