### ISSUE TITLE
Switch to GitHub releases as hosting service for source archive

### ISSUE THREAD

**Issue by pbek** [flathub/org.qownnotes.QOwnNotes#182]
Since the [TuxFamily](https://www.tuxfamily.org/) upload server has been very
unreliable and down for several days, we have now switched to GitHub releases
as hosting service for the source archive (see issue [#2799](https://github.com/pbek/QOwnNotes/issues/2799)).

The format of the source archive URL now looks like:
`https://github.com/pbek/QOwnNotes/releases/download/v23.7.0/qownnotes-23.7.0.tar.xz`

@stobbsm, who can migrate the automatic updater?

**Comment by Erick555** [comment]
Maybe this could work: https://github.com/flathub/org.qownnotes.QOwnNotes/pull/183

**Comment by pbek** [comment]
Not yet. 😅 
Thank you for taking that on!

**Comment by pbek** [comment]
@Erick555, do you care to test #184?
`flatpak install --user https://dl.flathub.org/build-repo/35588/org.qownnotes.QOwnNotes.flatpakref`

...this pattern should work better.

**Comment by pbek** [comment]
Ah, never mind. That will not test the updater, of course. 🙄

**Comment by pbek** [comment]
But I might have misunderstood what x-checker-data should return? A version number? A URL? Or both?

**Comment by Erick555** [comment]
It found the release but the `v` sign in version number confuses appstream.

**Comment by pbek** [comment]
the filter currently returns the whole url... how should the updater know where to download from?

**Comment by Erick555** [comment]
I think you may be able to strip `v` in `.tag_name` and re-add it in url construction. I'm not jq expert though

https://github.com/flathub/flatpak-external-data-checker#json-checker

https://jqlang.github.io/jq/

**Comment by pbek** [comment]
I totally overlooked `version-query`, thank you!

**Comment by pbek** [comment]
Finally, #187 arrived. Seems ok!
