### ISSUE TITLE
Flatpak update

### ISSUE THREAD

**Issue by andyhubbert941** [flathub/org.qownnotes.QOwnNotes#19]
For some reason flatpak hasn’t pulled in the updated version to flathub yet. Do we know why? Have I broken something? @pbek @stobbsm

**Comment by pbek** [comment]
I've no clue how the update process on flathub works, maybe @stobbsm is building the releases. 😅

**Comment by Erick555** [comment]
The build for arm []([failed](https://flathub.org/builds/#/builders/11/builds/4292)) although it may be temporary issue with flathub servers. You may go to https://flathub.org/builds/#/builders/32/builds/56367 login with github creds and restart the build.

**Comment by pbek** [comment]
> The build for arm failed although it may be temporary issue with flathub servers

`Upload build` failed...
I started a rebuild now.

**Comment by Erick555** [comment]
Now it succeeded and will be published within few hours.

**Comment by andyhubbert941** [comment]
all fixed now and built. I will try and keep on top of main code changes and submit pulls to keep up to date as able now it all seems to work!

**Comment by pbek** [comment]
Awesome, thank you 😁
