### ISSUE TITLE
Unable to set folders within home as note folders

### ISSUE THREAD

**Issue by ysteina** [flathub/org.qownnotes.QOwnNotes#2]
From the first-run wizard and from 'Note → Setup note folders' I am unable to use any folder within my home folder. The 'select folder' dialog simply does not respond when I select a folder and then choose 'Open'.

Flatpak 0.99.3
xdg-desktop-portal 0.11
xdg-desktop-portal-kde 5.13.2
OS: KDE Neon 5.13.2 (based on Ubuntu 16.04)

**Comment by stobbsm** [comment]
I must say, I've never experienced this issue. Can you run it from the command line in the flatpak to get some debug information for me?

https://blogs.gnome.org/mclasen/2017/01/20/debugging-a-flatpak-application/

That link will tell you how.

**Comment by ysteina** [comment]
Is a gdb run enough?

tarting program: /app/bin/QOwnNotes 
warning: File "/usr/lib/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /usr/lib/libthread_db-1.0.so
line to your configuration file "/home/oysteins/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/oysteins/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
warning: File "/usr/lib/libstdc++.so.6.0.22-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
Debug: main  - 'arguments':  ("/app/bin/QOwnNotes")
Debug: main  - 'locale':  "nn"
[New LWP 11]
[New LWP 12]
[New LWP 13]
[New LWP 14]
[New LWP 15]
Debug: getDiskDatabasePath  - 'databaseFileName':  "/home/oysteins/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotesDebug/QOwnNotes.sqlite"
Debug: setupTables  - 'database_version':  27
Debug: Set proxy configuration to use NO proxy
Debug: initShortcuts  - 'menuBarIsVisible':  true
Debug: initShortcuts  - 'menuBarIsVisible':  true
[New LWP 16]
Debug: buildNotesIndex  - 'noteSubFolderId':  0
Debug: setupNoteFolderTables  - 'database version':  13
Debug: loadNoteDirectoryList
Debug: reloadTagTree
Debug: reloadTagTree  - 'noteSubFolderIds':  (-1)
Debug: loadNoteDirectoryList
Debug: reloadTagTree
Debug: reloadTagTree  - 'noteSubFolderIds':  (-1)
Debug: reloadNoteSubFolderTree
Debug: reloadTagTree
Debug: reloadTagTree  - 'noteSubFolderIds':  (-1)
[New LWP 17]
Debug: reloadTagTree
Debug: reloadTagTree  - 'noteSubFolderIds':  (-1)
Debug: on_noteTreeWidget_currentItemChanged
Debug: setCurrentNote  - 'note':  Note: <id>1 <name>"Note 2018-07-14T20.31.05" <fileName>"Note 2018-07-14T20.31.05.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
Debug:  added to history:  NoteHistoryItem: <noteName>"Note 2018-07-14T20.31.05" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
Warning:   OpenType support missing for "Noto Sans", script 12 (text/qfontdatabase.cpp:951, QFontEngine* loadSingleEngine(int, const QFontDef&, QtFontFamily*, QtFontFoundry*, QtFontStyle*, QtFontSize*))
Warning:   OpenType support missing for "Noto Sans", script 11 (text/qfontdatabase.cpp:951, QFontEngine* loadSingleEngine(int, const QFontDef&, QtFontFamily*, QtFontFoundry*, QtFontStyle*, QtFontSize*))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
Warning: libpng warning: iCCP: known incorrect sRGB profile (image/qpnghandler.cpp:482, void qt_png_warning(png_structp, png_const_charp))
[LWP 15 exited]
[New LWP 18]

**Comment by stobbsm** [comment]
Sorry, travelling over the past week. I'll look through today and try to figure out what is missing. Does the problem only happen in the first run wizard?

**Comment by stobbsm** [comment]
Have you tried it with the new release? I bumped the runtime version number, which may fix it for you.

**Comment by ysteina** [comment]
It works now! (Tested on a clean install).

**Comment by stobbsm** [comment]
Good to hear!
