### ISSUE TITLE
Potential tool to automate updates

### ISSUE THREAD

**Issue by andyhubbert941** [flathub/org.qownnotes.QOwnNotes#49]
@Erick555 

I opened an issue for this so we can discuss it more. As per on the pull request I am unsure how to integrate the tool you specified to pull the updates to the code base automatically.

I'm not great with flatpak and still learning a lot!! If you have a specific example of how I would integrate x-checker to the current files let me know!

Currently the following needs to be updated each release:

- Link to binary
- SHA256 checksum
- Release file with date/time/version etc

Thanks!

**Comment by Erick555** [comment]
> Currently the following needs to be updated each release:
> 
>     Link to binary
>     SHA256 checksum
>     Release file with date/time/version etc
> 

This is exactly what [the](https://github.com/flathub/flatpak-external-data-checker) does. See examples usages on [flathub](https://github.com/flathub/flatpak-external-data-checker).
