### ISSUE TITLE
Need to rebuild 21.12.3

### ISSUE THREAD

**Issue by andyhubbert941** [flathub/org.qownnotes.QOwnNotes#55]
Build failed so hasn't been pushed to users. Looks like @pbek just needs to try build again please

**Comment by pbek** [comment]
Are you talking about https://github.com/flathub/org.qownnotes.QOwnNotes/pull/54? Where can I re-trigger a build?

**Comment by Erick555** [comment]
You can rebuild it [here](https://flathub.org/builds/#/builders/32/builds/70657) after log-in.

**Comment by pbek** [comment]
Thank you, running now.

**Comment by pbek** [comment]
https://flathub.org/builds/#/builders/32/builds/71104 went through
