### ISSUE TITLE
Why does updating org.qownnotes.QOwnNotes asks for additional permissions?

### ISSUE THREAD

**Issue by thejavascriptman** [flathub/org.qownnotes.QOwnNotes#75]
When running `flatpak update org.qownnotes.QOwnNotes` I get asked for new permissions, however after checking the git history of the `org.qownnotes.QOwnNotes.json` file, I see that `finish-args` has not been modified in a long time. 

QOwnNotes version before trying to update: 22.1.10.1

Command output:
```
$ flatpak update org.qownnotes.QOwnNotes
Looking for updates…

New org.qownnotes.QOwnNotes permissions:
    dbus access [1]

    [1] org.a11y.Bus, org.kde.kconfig.notify


        ID                                  Branch     Op Remote  Download
 1.     org.freedesktop.Platform.GL.default 21.08      u  flathub < 131.2 MB
 2.     org.kde.Platform.Locale             5.15-21.08 u  flathub < 345.0 MB (partial)
 3.     org.kde.Platform                    5.15-21.08 u  flathub < 305.1 MB
 4.     org.qownnotes.QOwnNotes.Locale      stable     u  flathub   < 2.9 MB (partial)
 5.     org.qownnotes.QOwnNotes             stable     u  flathub  < 18.1 MB

Proceed with these changes to the system installation? [Y/n]: n
```

* How come flatpak is asking for new permissions without `finish-args` being modified?
* What does `org.kde.kconfig.notify` do? (I couldn't find any documentation on the internet and `org.kde.kconfig.notify` does not appear on QDBusViewer)

**Comment by Erick555** [comment]
Those new permission come from KDE rutime which qonwnotes use and were recently added there: 

https://invent.kde.org/packaging/flatpak-kde-runtime/-/commit/4599a33182e5b7ed6eab6f35bf10a5f7598e13e0

https://invent.kde.org/packaging/flatpak-kde-runtime/-/commit/6382c41cedbac3698cb58f2769355e5eda939338

**Comment by thejavascriptman** [comment]
That explains everything, thanks a lot!
